version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
